### ISSUE TITLE
Plugin is incompatible

### ISSUE THREAD

**Issue by ghost** [Notloc/runelite-target-true-tile#1]
Plugin is no longer functioning and shows an error message "Plugin is incompatible and requires its author to update"
![image](https://github.com/Notloc/runelite-target-true-tile/assets/11243032/7b9354b0-9e5c-407b-b94c-3a23d1110862)

**Comment by Notloc** [comment]
PR for fix is up
https://github.com/runelite/plugin-hub/pull/6179

**Comment by Notloc** [comment]
PR was merged.
