### ISSUE TITLE
Teleporting sometimes causes ghost outlines to appear

### ISSUE THREAD

**Issue by Telope** [Notloc/runelite-target-true-tile#2]
I'm not exactly sure how to reproduce the bug. Just a best guess:

Steps to reproduce:

* Highlight NPC
* Click to interact with NPC
* Teleport away
* Hover NPC as you're teleporting

Expected Result: No outlines appear at teleport destination
Actual Result: ~5% of the time, the outlines persist in the new location. See image.

![image](https://github.com/Notloc/runelite-target-true-tile/assets/47144445/dfe77432-8eda-4750-804f-be982044e486)

These "ghost" outlines can be removed simply by switching the Target True Tile plugin off and on.

**Comment by ghost** [comment]
+1 this also happens to me for many monsters. Particularly notice it in my house after teleporting away

**Comment by Notloc** [comment]
Fixed in 1.2.1
Should be available on the plugin hub in a few days.

PR here:
https://github.com/runelite/plugin-hub/pull/6538
