### ISSUE TITLE
Stopped working on Araxxor

### ISSUE THREAD

**Issue by ghost** [Notloc/runelite-target-true-tile#4]
Noticed in the last couple days this plugin has stopped working at Araxxor.  Still works fine on other monsters though.

Still working on Araxytes:
![image](https://github.com/user-attachments/assets/75271961-3dce-4e81-bfd6-0be4502de0a7)

Not working on Araxxor for mouse-over or tagged

![image](https://github.com/user-attachments/assets/660c017f-0e4a-489b-adb5-a2ce57da32e4)

![image](https://github.com/user-attachments/assets/9d8ec3ec-fa96-47a6-9997-26895bd8a3f6)

![image](https://github.com/user-attachments/assets/e15f1ae3-617c-4735-85f1-debaae7fd891)

**Comment by Notloc** [comment]
Try enabling "Show for Friendly NPCs" for now.
Bosses don't seem to deliver their health bars in the same way as regular NPCs, so I can't detect them as hostile like normal.

**Comment by Notloc** [comment]
I made several changes for v1.3 that will hopefully fix this and other oddities.
However, I don't have the slayer level for Araxxor, so let me know.

PR is here:
https://github.com/runelite/plugin-hub/pull/6578

Usually takes a few days to get merged and hit the plugin hub.

**Comment by Notloc** [comment]
Realized I could just go visit Araxxor without the reqs.
Seems to be working now!
