### ISSUE TITLE
Compatibility with Corner Tile Indicators

### ISSUE THREAD

**Issue by Intecpsp** [Notloc/runelite-target-true-tile#5]
Is there any way to add [Corner Tile Indicators](https://github.com/geheur/Corner-Tile-Indicators) compatibility?

**Comment by Notloc** [comment]
No, I might be able to add it as a style option though.

**Comment by Notloc** [comment]
![image](https://github.com/user-attachments/assets/3ca8b9df-ecb7-4685-a94a-89a0f82dc5cb)
Will be available soonish.

**Comment by Intecpsp** [comment]
Awesome, thank you!
