### ISSUE TITLE
Compatibility with Monster HP Percentage

### ISSUE THREAD

**Issue by Arzbishop** [Notloc/runelite-target-true-tile#7]
I noticed this plugin is incompatible for me with Monster HP Percentage (https://github.com/lejeffe/MonsterHP). It affects the overlay which that plugin draws over the target. I already posted a comment there detailing this issue and incompatibility (see below).
https://github.com/lejeffe/MonsterHP/issues/40

**Comment by Notloc** [comment]
Thanks for the heads up! I've added my reasoning for my priority choice to the linked discussion.
Gonna close this issue for the time being, as I don't expect to be changing this plugin's overlay priority.

I am of course, open to further discussion in the linked thread and will revisit this if needed.
